### PR TITLE
all: change test loggers to zaptest

### LINKED ISSUE #151: all: switch test loggers to zaptest.Logger

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: Closes #151

---

## :construction_worker: Changes

This replaces all logger usages with `zaptest`, which pipes log output to `testing.T::Log`.

Why? Try [debugging this](https://travis-ci.com/ubclaunchpad/pinpoint/jobs/183612664). This change lets test failures *only* display the logs relevant to a failed test or test case, and makes log output compatible with `go test -v`.

## :flashlight: Testing Instructions

try `go test -v`, or fail a test on purpose and notice that not every test's output gets dumped out at the same time anymore

### CODE REVIEW

**Comment by bobheadxi** [comment]
this is most relevant to you @suujia !

**Comment by bobheadxi** [comment]
There's some strange race condition in `zaptest` - I've opened up https://github.com/uber-go/zap/issues/687 to ask about it

**Comment by bobheadxi** [comment]
Got an update which would explain the test failure:

https://github.com/uber-go/zap/issues/687#issuecomment-473382859

> t.Log is safe for concurrent use, but it's not safe to call t.Log as the test is ending, which I think is causing the race detector to go off. You should make sure that any background goroutines are stopped before the test ends.

**Comment by bobheadxi** [comment]
jk fixed it as of 4ed6ee7

**Review by bwdmonkey — APPROVED** [review]
LGTM

**Review by suujia — COMMENTED** [review]
dope

**Pull request merged**
