### PR TITLE
Add tests for gateway

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: n/a

---

## :construction_worker: Changes

Adds some tests for various bits and pieces for `gateway`

## :flashlight: Testing Instructions

```
go test ./...
```

### CODE REVIEW

**Review by bwdmonkey — COMMENTED** [review]
Two things:
1. Jest. I think it's trying to use global jest
```
( cd client ; npm run test )

> pinpoint-client@0.0.1 test /Users/tom/go/src/github.com/ubclaunchpad/pinpoint/client
> jest

sh: jest: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pinpoint-client@0.0.1 test: `jest`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the pinpoint-client@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2018-10-02T03_54_52_354Z-debug.log
make: *** [test] Error 1
tom:~/go/src/github.com/ubclaunchpad/pinpoint (test/gateway)$ jest
-bash: jest: command not found
tom:~/go/src/github.com/ubclaunchpad/pinpoint (test/gateway)$ npm install -g jest
/usr/local/bin/jest -> /usr/local/lib/node_modules/jest/bin/jest.js

> fsevents@1.2.4 install /usr/local/lib/node_modules/jest/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ jest@23.6.0
added 617 packages from 359 contributors in 6.212s
tom:~/go/src/github.com/ubclaunchpad/pinpoint (test/gateway)$ jest
Error: Could not find a config file based on provided values:
path: "/Users/tom/go/src/github.com/ubclaunchpad/pinpoint"
cwd: "/Users/tom/go/src/github.com/ubclaunchpad/pinpoint"
Config paths must be specified by either a direct path to a config
file, or a path to a directory. If directory is given, Jest will try to
traverse directory tree up, until it finds either "jest.config.js" or
"package.json".
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:97:11)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at resolveConfigPathByTraversing (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:101:10)
    at exports.default (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/resolveConfigPath.js:72:10)
    at readConfig (/Users/tom/go/src/github.com/ubclaunchpad/pinpoint/node_modules/jest-config/build/index.js:175:80)
```
2. `dep ensure`. This is more of a question or a possible issue. Switching from `test/local-dynamodb` to `test/gateway` and running `make ./...` threw an error something along the lines of `zap/zaptest/observer` not found blah blah. So I tried `make deps` but that threw another error
```
$ make deps
dep ensure
grouped write of manifest, lock and vendor: scratch directory /Users/tom/go/src/github.com/ubclaunchpad/pinpoint/.vendor-new already exists, please remove it
make: *** [deps] Error 1
```
Removing `.vendor-new/` did fix the issue, but I was wondering if this is a one-off or same case for other people.

**Comment by bobheadxi** [comment]
> Jest. I think it's trying to use global jest

did you run `make deps` or `cd client ; npm install` yet?

> dep ensure. This is more of a question or a possible issue. Switching from test/local-dynamodb to test/gateway and running make ./... threw an error something along the lines of zap/zaptest/observer not found blah blah

I've never tried `make ./...` and am not aware of what that might attempt to do, but I suspect that might be an issue. If you meant you ran `make deps` then I'm not sure.

**Comment by leesw98** [comment]
@bobheadxi Oh my bad about `make ./...` I meant `go test ./...`. And yea I ran `make deps`

**Comment by bobheadxi** [comment]
I've reproduced your issue - am looking into it. Strange, since travis seemed fine with it...

**Comment by bobheadxi** [comment]
@leesw98 give it another try:
- checkout master
- dep ensure
- checkout test/gateway
- dep ensure
- go test ./...

**Review by bwdmonkey — APPROVED** [review]
10/10

**Pull request merged**
