### PR TITLE
core <-> gateway TLS connections

### LINKED ISSUE #34: Set up TLS for core <-> gateway

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: Closes #34

---

## :construction_worker: Changes

- adds additional CLI options for setting core certificates and keys
- adds certs and keys for dev use
- minor improvements to logging, such as new coloured outputs:

image

## :flashlight: Testing Instructions

```
make core
make gateway
curl localhost:8081/status
```

### CODE REVIEW

**Comment by LynxHack** [comment]
I seem to be getting some weird runtime memory address nil pointer dereference error when starting up core with "make core". It was working very well just a while ago before I pulled the latest commit. I think it has to do with the signal calls?

image

**Comment by bobheadxi** [comment]
@LynxHack thanks, good catch! I've fixed this in 6cb031f

**Review by suujia — APPROVED** [review]
Great job, tech lead! 👍

**Review by LynxHack — APPROVED** [review]
Retested connection with TLS and everything seems to be working fine.

**Comment by bobheadxi** [comment]
Thanks!

**Pull request merged**
